name: home-automation

services:
  home-assistant:
    image: home-assistant
    pull_policy: never
    build:
      context: ./home-assistant
      dockerfile: Dockerfile
    container_name: home-assistant
    privileged: true
    restart: unless-stopped
    ports:
      - 51827:51827
    volumes:
      - ./home-assistant/config:/config
    environment:
      TZ: America/Los_Angeles

  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  swag:
    image: linuxserver/swag:arm32v7-2.6.0
    container_name: swag
    restart: unless-stopped
    ports:
      - 80:80
      - 8123:8123
    volumes:
      - ./swag/config:/config
    environment:
      PUID: 1000
      PGID: 1000
      URL: ${URL}
      EMAIL: ${EMAIL}
      VALIDATION: http
      TZ: America/Los_Angeles

  mdns-repeater:
    image: angelnu/mdns_repeater
    container_name: mdns-repeater
    restart: unless-stopped
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    environment:
      hostNIC: eth0
      dockerNIC: br-home

networks:
  default:
    name: home-automation
    driver_opts:
      com.docker.network.bridge.name: br-home
    ipam:
      config:
        - subnet: 172.16.1.0/24
